name: opensearch-stack
services:
  opensearch:
    image: opensearchproject/opensearch:3
    container_name: opensearch
    ports:
      - 9200:9200
      - 9600:9600
    environment:
      - discovery.type=single-node
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=PrinceCodeTalks@123
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    networks:
      - opensearch-network
  dashboard:
    image: opensearchproject/opensearch-dashboards:3
    container_name: dashboard
    ports:
      - 5601:5601
    environment:
      - OPENSEARCH_HOSTS=["https://opensearch:9200"]
      - OPENSEARCH_USERNAME=admin
      - OPENSEARCH_PASSWORD=PrinceCodeTalks@123
    networks:
      - opensearch-network
    depends_on:
      - opensearch
    
volumes:
  opensearch-data:
networks:
  opensearch-network: